In [69]:
import pandas as pd
import numpy as np

Read a JSON file that is generated by user_table.py

In [70]:
df = pd.read_json('output.json')

In [49]:
df

,Timestamp,Upload your photo!,Which question is this photo for?,Person 1 ID,Person 2 ID,Person 3 ID,Person 4 ID,Person 5 ID,Approved
0,2026-06-25 15:39:15.084000+00:00,https://drive.google.com/open?id=1eanFZGddjG0K...,1,1,2,,,,1

In [50]:
df.columns

Index(['Timestamp', 'Upload your photo!', 'Which question is this photo for?',
       'Person 1 ID', 'Person 2 ID', 'Person 3 ID', 'Person 4 ID',
       'Person 5 ID', 'Approved'],
      dtype='str')

In [71]:
df = df.rename(columns={'Upload your photo!': 'Link', 'Which question is this photo for?': 'Question'})
df.drop(columns=['Approved'], inplace=True)
# collapsed_df = pd.melt(df, id_vars=["Timestamp", "Link", "Question"], value_vars=[f" Person {i} ID" for i in range(1,6)], value_name="ID",).drop(columns=['variable'])

In [67]:
df

,Timestamp,Link,Question,Person 1 ID,Person 2 ID,Person 3 ID,Person 4 ID,Person 5 ID
0,2026-06-25 15:39:15.084000+00:00,https://drive.google.com/open?id=1eanFZGddjG0K...,1,1,2,,,

In [72]:
collapsed_df = pd.melt(
    df,
    id_vars=["Timestamp", "Link", "Question"],
    value_vars=[f"Person {i} ID" for i in range(1,6)],
    value_name="ID",)
collapsed_df["ID"] = (
    collapsed_df["ID"]
    .astype(str)
    .str.strip()
    .replace(["", "None", "NaN", "nan"], np.nan)
)
collapsed_df = collapsed_df.dropna(subset=["ID"])
collapsed_df = collapsed_df[['ID', 'Link', 'Question', 'Timestamp']]
collapsed_df

,ID,Link,Question,Timestamp
0,1,https://drive.google.com/open?id=1eanFZGddjG0K...,1,2026-06-25 15:39:15.084000+00:00
1,2,https://drive.google.com/open?id=1eanFZGddjG0K...,1,2026-06-25 15:39:15.084000+00:00

In [73]:
user_df = pd.read_json('user_table.json')
user_df

,ID,Link,Question,Timestamp
0,1,https://drive.google.com/open?id=1eanFZGddjG0K...,1,2026-06-25 15:39:15.084000+00:00
1,2,https://drive.google.com/open?id=1eanFZGddjG0K...,1,2026-06-25 15:39:15.084000+00:00

Create a DF from the JSON FILE to inspect the results here